### ISSUE TITLE
Issues with SMB Connector in certain flows(Connection TimeOut and invalid directory)

### ISSUE THREAD

**Issue by bhargavabinbev** [nuggetman/smb-connector#16]
Hi Alex,
We are facing the below issues in our SMB Connectors facing huge impacts in our business.The issue is occurring for the past one week. Any inputs on the below Error stack, will help us to troubleshoot the issue.,

16:10:20.533 07/02/2019 Worker-0 [abi-it2-evolution-bloomberg-prod].anaplan_upload_com.stage1.262 ERROR

********************************************************************************
Message : Failed to invoke directoryList.
Payload : 
Payload Type : java.lang.String
Element : /anaplan_upload_com/processors/0 @ abi-it2-evolution-bloomberg-prod
--------------------------------------------------------------------------------
Root Exception stack trace:
jcifs.smb.SmbException: The system cannot find the file specified. 

Cheers,
Bhargav.

**Comment by nuggetman** [comment]
Can you provide the complete stack trace? Also running the connector in debug mode would provide more insight by adding this to the log4j2.xml for the project: <AsyncLogger name="org.mule.modules.smb" level="DEBUG"/> 
On the surface of it the error message means that the connector cannot find the directory you are specifying.

**Comment by nuggetman** [comment]
I see the log files, etc on the Mule support case. Am investigating.

**Comment by bhargavabinbev** [comment]
Thanks Alex, I just want to update here that in On-Prem I have increased the JVM init and max memory in wrapper.conf to 3072 MB from 1024 MB. We are not seeing any issues for the past two days in file processing, however need to make sure if this will be a permanent fix as in the logs we could only figure out SMB exception. This is related to the issue reported to case number 00221833

For case number 00222885, there isn't any impacts now. But the issue is intermittent. 
Pls let me know if you need any additional details!

**Comment by nuggetman** [comment]
Understood, the soon to be released v1.2 of the connector has improvements for the wildcard filtering and should be more reliable in this regard.

**Comment by bhargavabinbev** [comment]
Thanks Alex, please keep me posted once v1.2 is available so that we can update in our app and test.

**Comment by bhargavabinbev** [comment]
Hi Alex,
Today we again had same issues, with no files being picked up from our SMB server. The ERROR stack showed the same issues, Connection timeout and system cannot find the file specified. Putting the ERROR stacks below,

[2019-07-15 13:15:12.381] DEBUG   org.mule.transport.sftp.SftpMessageRequester [[abi-it2-evolution-bloomberg-prod].misys_getmatchedfiles_it2Flow.stage1.05]: Routing file: 20190715090200957.RET_MSG_FILE.RTN
[2019-07-15 13:15:20.827] ERROR   org.mule.retry.notifiers.ConnectNotifier [[abi-it2-evolution-bloomberg-prod].anaplan_upload_com.stage1.05]: Failed to connect/reconnect: Work Descriptor. Root Exception was: The system cannot find the file specified.. Type: class jcifs.smb.SmbException
[2019-07-15 13:15:20.828] ERROR   org.mule.exception.DefaultMessagingExceptionStrategy [[abi-it2-evolution-bloomberg-prod].anaplan_upload_com.stage1.05]: 
********************************************************************************
Message               : Failed to invoke directoryList.
Payload               : 
Payload Type          : java.lang.String
Element               : /anaplan_upload_com/processors/0 @ abi-it2-evolution-bloomberg-prod
--------------------------------------------------------------------------------
Root Exception stack trace:
jcifs.smb.SmbException: The system cannot find the file specified.
	at jcifs.smb.SmbTransport.checkStatus(SmbTransport.java:542)
	at jcifs.smb.SmbTransport.send(SmbTransport.java:619)
	at jcifs.smb.SmbSession.send(SmbSession.java:242)
	at jcifs.smb.SmbTree.send(SmbTree.java:111)
	at jcifs.smb.SmbFile.send(SmbFile.java:729)
	at jcifs.smb.SmbFile.doFindFirstNext(SmbFile.java:1931)
	at jcifs.smb.SmbFile.doEnum(SmbFile.java:1683)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1660)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1626)
	at org.mule.modules.smb.internal.SmbClient.listDirectory(SmbClient.java:345)
	at org.mule.modules.smb.SmbConnector.directoryList(SmbConnector.java:97)
	at org.mule.modules.smb.generated.processors.DirectoryListMessageProcessor$1.process(DirectoryListMessageProcessor.java:133)
	at org.mule.security.oauth.process.ProcessCallbackProcessInterceptor.execute(ProcessCallbackProcessInterceptor.java:24)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:57)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:23)
	at org.mule.security.oauth.process.RetryProcessInterceptor.execute(RetryProcessInterceptor.java:84)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessTemplate.execute(ConnectionManagementProcessTemplate.java:36)
	at org.mule.modules.smb.generated.processors.DirectoryListMessageProcessor.doProcess(DirectoryListMessageProcessor.java:119)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:89)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:111)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.interceptor.AbstractEnvelopeInterceptor.processBlocking(AbstractEnvelopeInterceptor.java:59)
	at org.mule.processor.AbstractRequestResponseMessageProcessor.process(AbstractRequestResponseMessageProcessor.java:48)
	at org.mule.processor.AsyncInterceptingMessageProcessor.processNextTimed(AsyncInterceptingMessageProcessor.java:131)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:221)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:214)
	at org.mule.execution.ExecuteCallbackInterceptor.execute(ExecuteCallbackInterceptor.java:16)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:35)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:22)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:30)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:14)
	at org.mule.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:67)
	at org.mule.execution.ResolvePreviousTransactionInterceptor.execute(ResolvePreviousTransactionInterceptor.java:44)
	at org.mule.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:50)
	at org.mule.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:40)
	at org.mule.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:41)
	at org.mule.execution.ExternalTransactionInterceptor.execute(ExternalTransactionInterceptor.java:48)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:28)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:13)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:110)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:30)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker.doRun(AsyncInterceptingMessageProcessor.java:213)
	at org.mule.work.AbstractMuleEventWork.run(AbstractMuleEventWork.java:53)
	at org.mule.work.WorkerContext.run(WorkerContext.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
-----------------------------------------------

[2019-07-15 09:37:31.665] ERROR   org.mule.retry.notifiers.ConnectNotifier [[abi-it2-evolution-bloomberg-prod].it2_sendfiles_misysFlow.stage1.1804]: Failed to connect/reconnect: Work Descriptor. Root Exception was: Connection timeout. Type: class jcifs.smb.SmbException
[2019-07-15 09:37:31.665] WARN    org.mule.api.processor.LoggerMessageProcessor [[abi-it2-evolution-bloomberg-prod].it2_sendfiles_misysFlow.stage1.1804]: *** Connection timeout ****
[2019-07-15 09:38:01.675] ERROR   org.mule.retry.notifiers.ConnectNotifier [[abi-it2-evolution-bloomberg-prod].anaplan_upload_fx.stage1.1805]: Failed to connect/reconnect: Work Descriptor. Root Exception was: Connection timeout. Type: class jcifs.smb.SmbException
[2019-07-15 09:38:01.676] ERROR   org.mule.exception.DefaultMessagingExceptionStrategy [[abi-it2-evolution-bloomberg-prod].anaplan_upload_fx.stage1.1805]: 
********************************************************************************
Message               : Failed to invoke directoryList.
Payload               : 
Payload Type          : java.lang.String
Element               : /anaplan_upload_fx/processors/0 @ abi-it2-evolution-bloomberg-prod
--------------------------------------------------------------------------------
Root Exception stack trace:
jcifs.smb.SmbException: Connection timeout
jcifs.util.transport.TransportException: Connection timeout
	at jcifs.util.transport.Transport.connect(Transport.java:178)
	at jcifs.smb.SmbTransport.connect(SmbTransport.java:294)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:141)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:858)
	at jcifs.smb.SmbFile.connect(SmbFile.java:901)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:827)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1280)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1362)
	at jcifs.smb.SmbFile.canRead(SmbFile.java:1404)
	at org.mule.modules.smb.internal.SmbClient.connect(SmbClient.java:125)
	at org.mule.modules.smb.config.SmbConnectorConfig.connect(SmbConnectorConfig.java:186)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:34)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:10)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:47)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:19)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigConnectionManagementConnectionManager.acquireConnection(SmbConnectorConfigConnectionManagementConnectionManager.java:264)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigConnectionManagementConnectionManager.acquireConnection(SmbConnectorConfigConnectionManagementConnectionManager.java:44)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:48)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:23)
	at org.mule.security.oauth.process.RetryProcessInterceptor.execute(RetryProcessInterceptor.java:84)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessTemplate.execute(ConnectionManagementProcessTemplate.java:36)
	at org.mule.modules.smb.generated.processors.DirectoryListMessageProcessor.doProcess(DirectoryListMessageProcessor.java:119)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:89)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:111)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.processor.chain.DefaultMessageProcessorChain.doProcess(DefaultMessageProcessorChain.java:81)
	at org.mule.processor.chain.AbstractMessageProcessorChain.process(AbstractMessageProcessorChain.java:74)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.processor.AbstractInterceptingMessageProcessorBase.processNext(AbstractInterceptingMessageProcessorBase.java:99)
	at org.mule.interceptor.AbstractEnvelopeInterceptor.processBlocking(AbstractEnvelopeInterceptor.java:59)
	at org.mule.processor.AbstractRequestResponseMessageProcessor.process(AbstractRequestResponseMessageProcessor.java:48)
	at org.mule.processor.AsyncInterceptingMessageProcessor.processNextTimed(AsyncInterceptingMessageProcessor.java:131)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:221)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:214)
	at org.mule.execution.ExecuteCallbackInterceptor.execute(ExecuteCallbackInterceptor.java:16)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:35)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:22)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:30)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:14)
	at org.mule.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:67)
	at org.mule.execution.ResolvePreviousTransactionInterceptor.execute(ResolvePreviousTransactionInterceptor.java:44)
	at org.mule.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:50)
	at org.mule.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:40)
	at org.mule.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:41)
	at org.mule.execution.ExternalTransactionInterceptor.execute(ExternalTransactionInterceptor.java:48)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:28)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:13)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:110)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:30)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker.doRun(AsyncInterceptingMessageProcessor.java:213)
	at org.mule.work.AbstractMuleEventWork.run(AbstractMuleEventWork.java:53)
	at org.mule.work.WorkerContext.run(WorkerContext.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at jcifs.smb.SmbTransport.connect(SmbTransport.java:296)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:141)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:858)
	at jcifs.smb.SmbFile.connect(SmbFile.java:901)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:827)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1280)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1362)
	at jcifs.smb.SmbFile.canRead(SmbFile.java:1404)
	at org.mule.modules.smb.internal.SmbClient.connect(SmbClient.java:125)
	at org.mule.modules.smb.config.SmbConnectorConfig.connect(SmbConnectorConfig.java:186)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:34)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:10)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:47)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:19)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigConnectionManagementConnectionManager.acquireConnection(SmbConnectorConfigConnectionManagementConnectionManager.java:264)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigConnectionManagementConnectionManager.acquireConnection(SmbConnectorConfigConnectionManagementConnectionManager.java:44)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:48)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessInterceptor.execute(ConnectionManagementProcessInterceptor.java:23)
	at org.mule.security.oauth.process.RetryProcessInterceptor.execute(RetryProcessInterceptor.java:84)
	at org.mule.devkit.3.9.0.internal.connection.management.ConnectionManagementProcessTemplate.execute(ConnectionManagementProcessTemplate.java:36)
	at org.mule.modules.smb.generated.processors.DirectoryListMessageProcessor.doProcess(DirectoryListMessageProcessor.java:119)
	at org.mule.devkit.processor.DevkitBasedMessageProcessor.process(DevkitBasedMessageProcessor.java:89)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:111)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:88)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)
	at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:44)
	at org.mule.processor.BlockingProcessorExecutor.executeNext(BlockingProcessorExecutor.java:98)
	at org.mule.processor.BlockingProcessorExecutor.execute(BlockingProcessorExecutor.java:59)
	at org.mule.interceptor.AbstractEnvelopeInterceptor.processBlocking(AbstractEnvelopeInterceptor.java:59)
	at org.mule.processor.AbstractRequestResponseMessageProcessor.process(AbstractRequestResponseMessageProcessor.java:48)
	at org.mule.processor.AsyncInterceptingMessageProcessor.processNextTimed(AsyncInterceptingMessageProcessor.java:131)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:221)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:214)
	at org.mule.execution.ExecuteCallbackInterceptor.execute(ExecuteCallbackInterceptor.java:16)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:35)
	at org.mule.execution.CommitTransactionInterceptor.execute(CommitTransactionInterceptor.java:22)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:30)
	at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:14)
	at org.mule.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:67)
	at org.mule.execution.ResolvePreviousTransactionInterceptor.execute(ResolvePreviousTransactionInterceptor.java:44)
	at org.mule.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:50)
	at org.mule.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:40)
	at org.mule.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:41)
	at org.mule.execution.ExternalTransactionInterceptor.execute(ExternalTransactionInterceptor.java:48)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:28)
	at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:13)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:110)
	at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:30)
	at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker.doRun(AsyncInterceptingMessageProcessor.java:213)
	at org.mule.work.AbstractMuleEventWork.run(AbstractMuleEventWork.java:53)
	at org.mule.work.WorkerContext.run(WorkerContext.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

********************************************************************************
Is it possible to provide a tentative date for the updated version of Connector to be available or suggest an alternate fix until then as we are getting huge concerns from business here, as we are dealing with transferring treasury and transaction files :(

Thanks in advance!

Cheers,
Bhargav.

**Comment by bhargavabinbev** [comment]
Also, FYI Alex..
There isnt any connection timeout or reconnection strategy configured in the connector. Will configuring that helps?

**Comment by nuggetman** [comment]
By default (without you supplying a value) the connector will apply a 30 second timeout setting, specifying a higher value may be needed as the error you are getting is a timeout one.

As for a release date for the new edition, the connector is currently in review status and I am awaiting feedback from the certification team.

**Comment by bhargavabinbev** [comment]
Thanks for your feedback, Alex!

**Comment by bhargavabinbev** [comment]
Hi Alex,
Hope you are fine! Any idea on when SMB connector v1.2 will be available?

Cheers,
Bhargav.

**Comment by nuggetman** [comment]
Bhargav, connector v1.2 finished going through the certification process and is now released on Exchange: https://www.mulesoft.com/exchange/org.mule.modules/smb-connector/

**Comment by bhargavabinbev** [comment]
Thanks a lot for the update, Alex. Our applications are very well stable now, however we will try this update and let you know the outcomes.

@IT2MulesoftSupport<mailto:IT2MulesoftSupport@ab-inbev.com> team, Lets plan on updating the SMB connector version for our IT2 apps, test it and plan for next week’s RMB.

Cheers,
Bhargav.

**Comment by nuggetman** [comment]
Good stuff, will close this case for now, please open a fresh one if the new version causes any issues.
